<../../mkconfig

DIRS=\

TARG=\
	dumpbin.dis\

TESTTARG=\
	testexactus.dis\


SYSMODULES=\
	arg.m\
	draw.m\
	sys.m\

DISBIN=$ROOT/dis/basf

<$ROOT/mkfiles/mkdis

all:V:	$TARG $TESTTARG

dirs:V:
	mkdir $DISBIN
